# Generated by Django 4.2.1 on 2023-05-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='s_superuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
