# Generated by Django 4.2.1 on 2023-05-28 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 28, 20, 1, 1, 588707, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 28, 20, 1, 17, 822468, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
